Web/MegaCinema.Web/Controllers/CinemasController.cs
namespace MegaCinema.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using MegaCinema.Services.Data;
    using MegaCinema.Web.ViewModels.Cinema;
    using Microsoft.AspNetCore.Mvc;

    public class CinemasController : BaseController
    {
        private readonly ICinemaService cinemaService;

        public CinemasController(ICinemaService cinemaService)
        {
            this.cinemaService = cinemaService;
        }

        public IActionResult OurCinemas()
        {
            var viewModel = new CinemasAllViewModel
            {
                Cinemas = this.cinemaService.AllCinemas<CinemaViewModel>().ToList(),
            };
            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult Technologies()
        {
            return this.View();
        }

        public IActionResult DiningAndLobby()
        {
            return this.View();
        }

        public IActionResult All()
        {
            var viewModel = new CinemasAllViewModel
            {
                Cinemas = this.cinemaService.AllCinemas<CinemaViewModel>().ToList(),
            };
            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

Web/MegaCinema.Web/Controllers/MoviesController.cs
namespace MegaCinema.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using MegaCinema.Services.Data;
    using MegaCinema.Web.ViewModels.Movie;
    using Microsoft.AspNetCore.Mvc;

    public class MoviesController : BaseController
    {
        private readonly IMoviesService moviesService;

        public MoviesController(IMoviesService moviesService)
        {
            this.moviesService = moviesService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await this.moviesService.GetByIdAsync<MovieViewModel>(id);
            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult Available()
        {
            var viewModel = new AllMovieViewModel
            {
                AllMovies = this.moviesService.AllMovies<MovieViewModel>()
                .Where(x => x.ReleaseDate <= DateTime.UtcNow)
                .ToList(),
            };

            return this.View(viewModel);
        }

        public IActionResult Upcoming()
        {
            var viewModel = new AllMovieViewModel
            {
                AllMovies = this.moviesService.AllMovies<MovieViewModel>()
                .Where(x => x.ReleaseDate > DateTime.UtcNow)
                .ToList(),
            };

            return this.View(viewModel);
        }
    }
}

Web/MegaCinema.Web/Controllers/ProjectionsController.cs
namespace MegaCinema.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using MegaCinema.Data;

    using MegaCinema.Services.Data;
    using MegaCinema.Web.ViewModels.Projection;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;

    public class ProjectionsController : BaseController
    {
        private const string ErrorBeforeToday = "Date connot be before current date";
        private readonly IProjectionsService projectionsService;
        private readonly IMoviesService moviesService;
        private readonly ICinemaService cinemaService;

        public ProjectionsController(
            IProjectionsService projectionsService,
            IMoviesService moviesService,
            ICinemaService cinemaService)
        {
            this.projectionsService = projectionsService;
            this.moviesService = moviesService;
            this.cinemaService = cinemaService;
        }

        public IActionResult All()
        {
            var viewModel = new AllProjectionsViewModel
            {
                AllProjections = this.projectionsService.AllProjections<ProjectionViewModel>().ToList(),
            };

            return this.View(viewModel);
        }

        public IActionResult ByCinemaForToday(string cinemaName)
        {
            var viewModel = new AllProjectionsViewModel
            {
                AllProjections = this.projectionsService
                .AllProjectionsByCinema<ProjectionViewModel>(cinemaName)
                .ToList(),
            };

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult ByProjectionId(int id)
        {
            var viewModel = this.projectionsService
                .ProjectionByProjectionId<ProjectionViewModel>(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult ByMovieId(int id)
        {
            var viewModel = new AllProjectionsViewModel
            {
                AllProjections = this.projectionsService
                .ProjectionByMovieId<ProjectionViewModel>(id)
                .ToList(),
            };

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        public IActionResult FindProjection(int? movieId)
        {
            var viewModel = new FindProjectionInputModel();
            IEnumerable<MovieDropdownModel> movies;
            IEnumerable<CinemaDropdownModel> cinemas;

            if (movieId == null)
            {
                movies = this.moviesService.AllMovies<MovieDropdownModel>()
                        .Where(x => x.ReleaseDate.DayOfYear < DateTime.UtcNow.DayOfYear);
                cinemas = this.cinemaService.AllCinemas<CinemaDropdownModel>();
            }
            else
            {
                var movie = this.moviesService.MovieExist(movieId.Value);
                if (movie == false)
                {
                    movies = this.moviesService.AllMovies<MovieDropdownModel>()
                        .Where(x => x.ReleaseDate.DayOfYear < DateTime.UtcNow.DayOfYear);
                    cinemas = this.cinemaService.AllCinemas<CinemaDropdownModel>();
                }
                else
                {
                    movies = this.moviesService.AllMovies<MovieDropdownModel>()
                            .Where(x => x.Id == movieId);
                    cinemas = this.cinemaService.AllCinemas<CinemaDropdownModel>();
                }
            }

            viewModel.Cinemas = cinemas;
            viewModel.Movies = movies;
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult FoundProjectionsResult(int cinemaId, int? movieId, DateTime? starttime)
        {
            var projectionsList = new List<ProjectionViewModel>();
            var viewModel = new AllProjectionsViewModel();
            int movieIdToFind = 0;
            DateTime toFind = DateTime.UtcNow;

            if (starttime.HasValue)
            {
                DateTime haveDate = starttime.Value;
                if (haveDate.DayOfYear < toFind.DayOfYear)
                {
                    this.ModelState.AddModelError(string.Empty, ErrorBeforeToday);
                    var movies = this.moviesService.AllMovies<MovieDropdownModel>();
                    var cinemas = this.cinemaService.AllCinemas<CinemaDropdownModel>();

                    var inputViewModel = new FindProjectionInputModel
                    {
                        Cinemas = cinemas,
                        Movies = movies,
                    };

                    return this.RedirectToAction("FindProjection", inputViewModel);
                }
            }

            if (starttime == null && movieId != null)
            {
                movieIdToFind = movieId ?? default;
                projectionsList = this.projectionsService
                    .ProjectionByMovieIdAndCinemaIdOnly<ProjectionViewModel>(movieIdToFind, cinemaId)
                    .ToList();
                viewModel.AllProjections = projectionsList;
                return this.View(viewModel);
            }
            else
            {
                toFind = starttime ?? DateTime.UtcNow;
            }

            if (movieId == null)
            {
                if (toFind.DayOfYear == DateTime.UtcNow.DayOfYear)
                {
                    projectionsList = this.projectionsService
                    .ProjectionByCinemaIdAndDate<ProjectionViewModel>(cinemaId, toFind)
                    .Where(x => x.StartTime.Hour > DateTime.UtcNow.AddHours(3).Hour)
                    .ToList();
                }
                else
                {
                    projectionsList = this.projectionsService
                        .ProjectionByCinemaIdAndDate<ProjectionViewModel>(cinemaId, toFind)
                        .ToList();
                }
            }
            else
            {
                if (toFind.DayOfYear == DateTime.UtcNow.DayOfYear)
                {
                    projectionsList = this.projectionsService
                    .ProjectionByMovieIdAdCinemaId<ProjectionViewModel>((int)movieId, cinemaId, toFind)
                    .Where(x => x.StartTime.Hour > DateTime.UtcNow.AddHours(3).Hour)
                    .ToList();
                }
                else
                {
                    projectionsList = this.projectionsService
                        .ProjectionByMovieIdAdCinemaId<ProjectionViewModel>((int)movieId, cinemaId, toFind)
                        .ToList();
                }
            }

            viewModel.AllProjections = projectionsList;

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

Web/MegaCinema.Web/Controllers/TicketsController.cs
namespace MegaCinema.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using MegaCinema.Data.Models;
    using MegaCinema.Services.Data;
    using MegaCinema.Web.ViewModels.Ticket;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class TicketsController : BaseController
    {
        private const int PostsPerPageDefaultValue = 10;
        private const string OccupiedSeat = "This seat is already occupied";
        private readonly ITicketsService ticketsService;
        private readonly UserManager<ApplicationUser> userManager;

        public TicketsController(
            ITicketsService ticketsService,
            UserManager<ApplicationUser> userManager)
        {
            this.ticketsService = ticketsService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult BookTicket(int projectionId)
        {
            var viewModel = this.ticketsService.GetTicketDetails(projectionId);
            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> BookTicket(TicketViewModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var userId = user.Id;

            var result = await this.ticketsService.AddTicketAndSeat(
                inputModel.ProjectionId,
                userId,
                inputModel.Row,
                inputModel.SeatNumer,
                inputModel.Price);

            if (result < 0)
            {
                this.ModelState.AddModelError(string.Empty, OccupiedSeat);
                return this.View(inputModel);
            }

            return this.RedirectToAction("BookedTicketDetails", new { ticketId = result });
        }

        [Authorize]
        public IActionResult BookedTicketDetails(int ticketId)
        {
            var viewModel = this.ticketsService.ShowBookedTicket(ticketId);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult HistoryTicketDetails(int ticketId)
        {
            var viewModel = this.ticketsService.ShowBookedTicket(ticketId);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> MyTickets(int page = 1, int perPage = PostsPerPageDefaultValue)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var userId = user.Id;
            var ticketForUser = this.ticketsService.ShowAllMyTickets()
                .Where(x => x.UserId == userId)
                .OrderBy(x => x.CreatedOn);

            var pagesCount = (int)Math.Ceiling(ticketForUser.Count() / (decimal)perPage);

            var viewModel = new AllMyTicketsViewModel
            {
                CurrentPage = page,
                PagesCount = pagesCount,
                AllTickets = ticketForUser.Skip(perPage * (page - 1)).Take(perPage),
            };

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

Web/MegaCinema.Web/Views/Shared/_AnimatedCarrousel.cshtml
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>

    <div id="demo" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
            <li data-target="#demo" data-slide-to="3"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item">
                <img src="https://i.imgur.com/RX4FQLb.jpg" alt="Harley Quinn" width="1100" height="500">
                <div class="carousel-caption">
                    <h3>Harley Quinn</h3>
                    <p>As crazy as always</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://i.imgur.com/SpMHLAB.jpg" alt="Bloodshot " width="1100" height="500">
                <div class="carousel-caption">
                    <h3>Bloodshot </h3>
                    <p>
                        Ray Garrison, a slain soldier, is re-animated with superpowers.
                    </p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="https://i.imgur.com/HpT6mlL.jpg" alt="Black Widow" width="1100" height="500">
                <div class="carousel-caption">
                    <h3> Black Widow  </h3>
                    <p>
                        A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.
                    </p>
                </div>
            </div>
            <div class="carousel-item active">
                <img src="https://i.imgur.com/RTC68TA.jpg" alt="Jumanji" width="1100" height="500">
                <div class="carousel-caption">
                    <h3>Jumanji</h3>
                    <p>New adventures ahead!</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>

</body>
</html>

Web/MegaCinema.Web/Views/Shared/_CarouselMoviePartial.cshtml
@using MegaCinema.Common
@using MegaCinema.Web.ViewModels.Home;
@model IndexAllMoviesViewModel

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/css/images/emma.jpg" class="d-block col-md-4" alt="poster">
            </div>
            <div class="carousel-item">
                <img src="~/css/images/jumanji.jpg" width="300" class="d-block col-md-4" alt="poster">
            </div>
            <div class="carousel-item">
                <img src="~/css/images/thewayback.jpg" width="300" class="d-block col-md-4" alt="poster">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

Web/MegaCinema.Web/Views/Shared/_Layout.cshtml
@using MegaCinema.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
        <link rel="shortcut icon" href="~/myfavicon.ico" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
        <link rel="shortcut icon" href="~/myfavicon.ico" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Tickets" asp-action="MyTickets">My Tickets</a>
                            </li>
                        </ul>
                    }


                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Movies
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Available">In Theatres</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Upcoming">Coming Soon</a>
                        </div>
                    </div>

                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About Us
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Cinemas" asp-action="OurCinemas">Our Cinemas</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Cinemas" asp-action="Technologies">Technologies</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Cinemas" asp-action="DiningAndLobby">Dining</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>

                        </div>
                    </div>

                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Projections
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Projections" asp-action="ByCinemaForToday" asp-route-cinemaname="Varna">Varna</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Projections" asp-action="ByCinemaForToday" asp-route-cinemaname="Burgas">Burgas</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Projections" asp-action="ByCinemaForToday" asp-route-cinemaname="Sofia">Sofia</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Projections" asp-action="ByCinemaForToday" asp-route-cinemaname="Plovdiv">Plovdiv</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Projections" asp-action="FindProjection" >Search</a>
                        </div>
                    </div>

                    @if (User.IsInRole("Administrator"))
                    {
                        @*<li class="navbar-nav flex-grow-1">
                     <a asp-controller="Home" asp-action="Index" asp-area="Administration" class="nav-link"><i class="fas fa-user-cog"></i>Administration</a>
                </li>*@

                        <div class="dropdown show">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Administration
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-area="Administration" asp-controller="Movies" asp-action="Index">Movies</a>
                                <a class="dropdown-item" asp-area="Administration" asp-controller="Projections" asp-action="Index">Projections</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>


        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @this.RenderBody()
            </main>
        </div>


    <footer class="border-top navbar-dark bg-dark footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>